### ISSUE TITLE
メトロポリスを読み込まないオプションのエラーについて

### ISSUE THREAD

**Issue by uip-kleh** [spica-jp/LaTeX_Packages#1]
# 
\usepackage[notloadtheme]{skmetro}として実行したところ以下のエラーが出力されました。
```bash:
(/usr/local/texlive/2022/texmf-dist/tex/latex/beamer/beamerinnerthemecircles.st
y)
! Undefined control sequence.
<argument> \metropolis@titleseparator@linewidth 
                                     
l.153 ...{\metropolis@titleseparator@linewidth}{1pt}
```
実行環境は
This is LuaHBTeX, Version 1.15.0 (TeX Live 2022) 
です。

**Comment by yasuak1** [comment]
# blockの色が反映されない件について
重ねて申し訳ありません。blockの機能を使用したところメインテーマの色が反映されません。

**Comment by spicajp** [comment]
情報提供，ありがとうございます。

`\metropolis@titleseparator@linewidth`などはmetropolisで提供されるものなので，`\usetheme{metropolis}`した状態でないと「`\metropolis@titleseparator@linewidth`なんて定義されてませんよ」と言われてしまう形です。

確かにそこの処理は甘かったので，`skmetro.sty`に修正を加え，対処しておきました。
